### ISSUE TITLE
Items with NBT attached data causes NullPointerException

### ISSUE THREAD

**Issue by AzureDoom** [AustereTony-MCMods/Oxygen-Merchants#2]
**Oxygen-Merchants version:** 
oxygen-merchants-1.12.2-0.1.1

**Current behavior:** 
Adding any item with NBT data to shop causes the shop data to corrupt for the whole server, requiring a shop wipe.

**Expected behavior:**
Item keeps NBT data and another of the same item but with different nbt data not overwrite the old one. 

**Steps to reproduce:**
Add an item to a shop (I use [Mine and Slash](https://www.curseforge.com/minecraft/mc-mods/mine-and-slash-reloaded/files/2748154), which gives stats to items via NBT data in the correct way). Upon server restart or disconnect or reconnect, the shop is unable to be viewed and any attempt to access the management panel causes an NullPointerException.  

**Related log info:**
`[00:00:27] [oxygen_merchants network/ERROR] [Oxygen Core]: Caught exception from thread: oxygen_merchants network.
[00:00:27] [oxygen_merchants network/INFO] [STDERR]: [austeretony.oxygen.common.delegate.OxygenThread:run:28]: java.lang.NullPointerException
[00:00:27] [oxygen_merchants network/INFO] [STDERR]: [austeretony.oxygen.common.delegate.OxygenThread:run:28]:  at austeretony.oxygen_merchants.common.network.client.CPSyncDataOpenMenu.write(CPSyncDataOpenMenu.java:28)
[00:00:27] [oxygen_merchants network/INFO] [STDERR]: [austeretony.oxygen.common.delegate.OxygenThread:run:28]:  at austeretony.oxygen.common.api.network.OxygenNetwork.pack(OxygenNetwork.java:86)
[00:00:27] [oxygen_merchants network/INFO] [STDERR]: [austeretony.oxygen.common.delegate.OxygenThread:run:28]:  at austeretony.oxygen.common.api.network.OxygenNetwork.access$100(OxygenNetwork.java:23)
[00:00:27] [oxygen_merchants network/INFO] [STDERR]: [austeretony.oxygen.common.delegate.OxygenThread:run:28]:  at austeretony.oxygen.common.api.network.OxygenNetwork$4.execute(OxygenNetwork.java:115)
[00:00:27] [oxygen_merchants network/INFO] [STDERR]: [austeretony.oxygen.common.delegate.OxygenThread:run:28]:  at austeretony.oxygen.common.delegate.OxygenThread.run(OxygenThread.java:25)`

**Comment by AzureDoom** [comment]
This issue was fixed in a2655b7a6a0bb85135d0cca712335323c444de82
